// Decants data — 10ml decant prices
// Source: Excel Decants.xlsx "Desglose Decants" sheet

export type DecantBrand = "Armaf" | "Lattafa" | "Zimaya";
export type DecantGender = "Dama" | "Caballero" | "Unisex";

export interface Decant {
  name: string;
  brand: DecantBrand;
  size: number; // bottle size in ml
  gender: DecantGender;
  price: number; // decant 10ml price in $
  perfumeId: number | null; // links to perfume catalog (for images)
  fragranticaId: number | null; // for Fragrantica image URLs
}

export const DECANT_BRANDS: DecantBrand[] = ["Armaf", "Lattafa", "Zimaya"];
export const DECANT_GENDERS: DecantGender[] = ["Dama", "Caballero", "Unisex"];

export const DECANTS: Decant[] = [
  // ==================== ARMAF (41) ====================
  { name: "Beach Party", brand: "Armaf", size: 100, gender: "Unisex", price: 15, perfumeId: null, fragranticaId: 102025 },
  { name: "Club de Nuit Bling", brand: "Armaf", size: 105, gender: "Unisex", price: 14, perfumeId: 203, fragranticaId: 117624 },
  { name: "Club de Nuit Iconic", brand: "Armaf", size: 105, gender: "Caballero", price: 12, perfumeId: 115, fragranticaId: 78475 },
  { name: "Club de Nuit Imperial", brand: "Armaf", size: 105, gender: "Dama", price: 14, perfumeId: null, fragranticaId: 78474 },
  { name: "Club de Nuit Intense Man", brand: "Armaf", size: 105, gender: "Caballero", price: 13, perfumeId: 1, fragranticaId: 34696 },
  { name: "Club de Nuit Intense Woman", brand: "Armaf", size: 105, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 27656 },
  { name: "Club de Nuit Maleka", brand: "Armaf", size: 105, gender: "Dama", price: 15, perfumeId: 119, fragranticaId: 106168 },
  { name: "Club de Nuit Precieux", brand: "Armaf", size: 55, gender: "Caballero", price: 26, perfumeId: null, fragranticaId: 93272 },
  { name: "Club de Nuit Precieux Dama", brand: "Armaf", size: 55, gender: "Dama", price: 26, perfumeId: null, fragranticaId: 115124 },
  { name: "Club de Nuit Sillage", brand: "Armaf", size: 105, gender: "Caballero", price: 16, perfumeId: 116, fragranticaId: 64105 },
  { name: "Club de Nuit Urban Man", brand: "Armaf", size: 105, gender: "Caballero", price: 16, perfumeId: 118, fragranticaId: 47394 },
  { name: "Club de Nuit Urban Milestone", brand: "Armaf", size: 100, gender: "Unisex", price: 14, perfumeId: null, fragranticaId: 64104 },
  { name: "Club de Nuit Woman Extrait", brand: "Armaf", size: 105, gender: "Dama", price: 14, perfumeId: null, fragranticaId: 102814 },
  { name: "El Cielo", brand: "Armaf", size: 100, gender: "Unisex", price: 13, perfumeId: null, fragranticaId: 50321 },
  { name: "Eter Desert Sky", brand: "Armaf", size: 100, gender: "Unisex", price: 17, perfumeId: null, fragranticaId: 92890 },
  { name: "Hunter", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 27695 },
  { name: "Island Bliss", brand: "Armaf", size: 100, gender: "Dama", price: 15, perfumeId: 144, fragranticaId: 98718 },
  { name: "Le Parfait Azure History", brand: "Armaf", size: 100, gender: "Unisex", price: 11, perfumeId: null, fragranticaId: 77872 },
  { name: "Lionheart Woman", brand: "Armaf", size: 100, gender: "Dama", price: 15, perfumeId: null, fragranticaId: 102027 },
  { name: "Mandarin Sky", brand: "Armaf", size: 100, gender: "Caballero", price: 13, perfumeId: null, fragranticaId: 83132 },
  { name: "Mandarin Sky Elixir", brand: "Armaf", size: 200, gender: "Unisex", price: 11, perfumeId: null, fragranticaId: 106709 },
  { name: "Miss Catwalk", brand: "Armaf", size: 100, gender: "Dama", price: 14, perfumeId: null, fragranticaId: 87098 },
  { name: "Miss Chic", brand: "Armaf", size: 100, gender: "Dama", price: 13, perfumeId: null, fragranticaId: 87097 },
  { name: "Odyssey Bahama", brand: "Armaf", size: 100, gender: "Unisex", price: 15, perfumeId: null, fragranticaId: 115127 },
  { name: "Odyssey Black Forest", brand: "Armaf", size: 100, gender: "Unisex", price: 14, perfumeId: 211, fragranticaId: 115125 },
  { name: "Odyssey Candee", brand: "Armaf", size: 100, gender: "Dama", price: 12, perfumeId: 208, fragranticaId: 96990 },
  { name: "Odyssey Dubai Chocolate", brand: "Armaf", size: 100, gender: "Caballero", price: 14, perfumeId: 213, fragranticaId: 102117 },
  { name: "Odyssey Go Mango", brand: "Armaf", size: 100, gender: "Unisex", price: 14, perfumeId: 210, fragranticaId: 115130 },
  { name: "Odyssey Limoni", brand: "Armaf", size: 100, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 98695 },
  { name: "Odyssey Marshmallow", brand: "Armaf", size: 100, gender: "Unisex", price: 12, perfumeId: 209, fragranticaId: 115132 },
  { name: "Odyssey Mega", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: 113, fragranticaId: 83133 },
  { name: "Odyssey Revolution", brand: "Armaf", size: 100, gender: "Unisex", price: 15, perfumeId: 212, fragranticaId: 109770 },
  { name: "Odyssey Toffee", brand: "Armaf", size: 100, gender: "Unisex", price: 15, perfumeId: null, fragranticaId: 115137 },
  { name: "Odyssey Tyrant", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: 207, fragranticaId: 83135 },
  { name: "Odyssey Wild One", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 83137 },
  { name: "Space Age", brand: "Armaf", size: 100, gender: "Unisex", price: 13, perfumeId: null, fragranticaId: 93742 },
  { name: "Tag Nero", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 90410 },
  { name: "Tag Rosso", brand: "Armaf", size: 100, gender: "Caballero", price: 13, perfumeId: null, fragranticaId: 90407 },
  { name: "Ventana", brand: "Armaf", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 90658 },

  // ==================== LATTAFA (78) ====================
  { name: "Ajwaa", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 56, fragranticaId: 85368 },
  { name: "Al Haramain Carbon", brand: "Lattafa", size: 60, gender: "Unisex", price: 27, perfumeId: null, fragranticaId: 73207 },
  { name: "Al Haramain Gold Edition 100ml", brand: "Lattafa", size: 100, gender: "Unisex", price: 19, perfumeId: null, fragranticaId: 51816 },
  { name: "Al Haramain Oud White", brand: "Lattafa", size: 60, gender: "Unisex", price: 25, perfumeId: null, fragranticaId: 73210 },
  { name: "Al Haramain Ruby 120ml", brand: "Lattafa", size: 120, gender: "Unisex", price: 17, perfumeId: null, fragranticaId: 73208 },
  { name: "Al Noble Safer", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 82795 },
  { name: "Amethyst", brand: "Lattafa", size: 100, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 68214 },
  { name: "Ana Abiyedh", brand: "Lattafa", size: 60, gender: "Unisex", price: 13, perfumeId: null, fragranticaId: 59149 },
  { name: "Ana Abiyedh Coral", brand: "Lattafa", size: 60, gender: "Dama", price: 14, perfumeId: 217, fragranticaId: 103256 },
  { name: "Ana Abiyedh Poudree", brand: "Lattafa", size: 60, gender: "Dama", price: 13, perfumeId: null, fragranticaId: 84590 },
  { name: "Ansaam Gold", brand: "Lattafa", size: 100, gender: "Dama", price: 13, perfumeId: 30, fragranticaId: 82731 },
  { name: "Asad", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: 134, fragranticaId: 72821 },
  { name: "Asad Bourbon", brand: "Lattafa", size: 100, gender: "Caballero", price: 13, perfumeId: 135, fragranticaId: 101124 },
  { name: "Asad Elixir", brand: "Lattafa", size: 100, gender: "Caballero", price: 14, perfumeId: 29, fragranticaId: 117616 },
  { name: "Atlas", brand: "Lattafa", size: 75, gender: "Caballero", price: 15, perfumeId: null, fragranticaId: 89765 },
  { name: "Berry On Top", brand: "Lattafa", size: 100, gender: "Unisex", price: 16, perfumeId: 43, fragranticaId: 114395 },
  { name: "Choco Overdose", brand: "Lattafa", size: 100, gender: "Unisex", price: 16, perfumeId: 44, fragranticaId: 114398 },
  { name: "Dinasty", brand: "Lattafa", size: 100, gender: "Caballero", price: 13, perfumeId: 61, fragranticaId: 112859 },
  { name: "Eclaire", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 219, fragranticaId: 93628 },
  { name: "Eclaire Banoffi", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 19, fragranticaId: 113778 },
  { name: "Eclaire Pistache", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 18, fragranticaId: 113777 },
  { name: "Efeef", brand: "Lattafa", size: 100, gender: "Dama", price: 13, perfumeId: 50, fragranticaId: 100126 },
  { name: "Emaan", brand: "Lattafa", size: 100, gender: "Unisex", price: 11, perfumeId: 66, fragranticaId: 85091 },
  { name: "Emeer", brand: "Lattafa", size: 100, gender: "Unisex", price: 15, perfumeId: 149, fragranticaId: 89761 },
  { name: "Eternal Vanille", brand: "Lattafa", size: 100, gender: "Dama", price: 16, perfumeId: 59, fragranticaId: 119155 },
  { name: "Fakhar Gold", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 128690 },
  { name: "Fakhar Platin", brand: "Lattafa", size: 100, gender: "Unisex", price: 12, perfumeId: 215, fragranticaId: 107363 },
  { name: "Fakhar Rose", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 22, fragranticaId: 70466 },
  { name: "Fakhar Silver", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 107363 },
  { name: "Fire On Ice", brand: "Lattafa", size: 100, gender: "Caballero", price: 13, perfumeId: null, fragranticaId: 111414 },
  { name: "Hayaati", brand: "Lattafa", size: 100, gender: "Caballero", price: 11, perfumeId: 146, fragranticaId: 75902 },
  { name: "Hayaati Florence", brand: "Lattafa", size: 100, gender: "Dama", price: 11, perfumeId: 27, fragranticaId: 84769 },
  { name: "Her Confession", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 54, fragranticaId: 96864 },
  { name: "His Confession", brand: "Lattafa", size: 100, gender: "Caballero", price: 15, perfumeId: 55, fragranticaId: 96866 },
  { name: "Honor y Glory", brand: "Lattafa", size: 100, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 84302 },
  { name: "Jassor", brand: "Lattafa", size: 100, gender: "Unisex", price: 13, perfumeId: 60, fragranticaId: 85093 },
  { name: "Khamrah", brand: "Lattafa", size: 100, gender: "Unisex", price: 13, perfumeId: 128, fragranticaId: 75805 },
  { name: "Khamrah Dukhan", brand: "Lattafa", size: 100, gender: "Caballero", price: 14, perfumeId: 130, fragranticaId: 104529 },
  { name: "Khamrah Qawha", brand: "Lattafa", size: 100, gender: "Caballero", price: 13, perfumeId: 129, fragranticaId: 88175 },
  { name: "Layaan", brand: "Lattafa", size: 100, gender: "Dama", price: 14, perfumeId: 49, fragranticaId: 117123 },
  { name: "Mallow Madness", brand: "Lattafa", size: 100, gender: "Unisex", price: 16, perfumeId: 45, fragranticaId: 114396 },
  { name: "Mayar", brand: "Lattafa", size: 100, gender: "Dama", price: 13, perfumeId: null, fragranticaId: 84309 },
  { name: "Mayar Cherry", brand: "Lattafa", size: 100, gender: "Dama", price: 13, perfumeId: 218, fragranticaId: 99872 },
  { name: "Mayar Natural Intense", brand: "Lattafa", size: 100, gender: "Dama", price: 11, perfumeId: 20, fragranticaId: 89759 },
  { name: "Mohra", brand: "Lattafa", size: 100, gender: "Unisex", price: 11, perfumeId: null, fragranticaId: 78382 },
  { name: "Mohra Silky Rose", brand: "Lattafa", size: 100, gender: "Dama", price: 11, perfumeId: null, fragranticaId: 78383 },
  { name: "Nebras Elixir", brand: "Lattafa", size: 100, gender: "Dama", price: 15, perfumeId: 28, fragranticaId: 85091 },
  { name: "Noble Blush", brand: "Lattafa", size: 100, gender: "Dama", price: 13, perfumeId: null, fragranticaId: 98937 },
  { name: "Now Pink", brand: "Lattafa", size: 100, gender: "Dama", price: 10, perfumeId: null, fragranticaId: 85088 },
  { name: "Opulent Dubai", brand: "Lattafa", size: 100, gender: "Unisex", price: 14, perfumeId: 150, fragranticaId: 105609 },
  { name: "Oud For Glory", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: null, fragranticaId: 64948 },
  { name: "Pisa", brand: "Lattafa", size: 100, gender: "Caballero", price: 14, perfumeId: null, fragranticaId: 99140 },
  { name: "Qaed Al Fursan Untamed", brand: "Lattafa", size: 90, gender: "Caballero", price: 12, perfumeId: 25, fragranticaId: 105383 },
  { name: "Qimmah", brand: "Lattafa", size: 100, gender: "Caballero", price: 10, perfumeId: 67, fragranticaId: 82793 },
  { name: "Ramz Gold", brand: "Lattafa", size: 100, gender: "Dama", price: 10, perfumeId: 73, fragranticaId: 70368 },
  { name: "Ramz Silver", brand: "Lattafa", size: 100, gender: "Unisex", price: 10, perfumeId: 72, fragranticaId: 71868 },
  { name: "Rave Now", brand: "Lattafa", size: 100, gender: "Caballero", price: 11, perfumeId: 88, fragranticaId: 82467 },
  { name: "Rave Now Intense", brand: "Lattafa", size: 100, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 82468 },
  { name: "Sehr", brand: "Lattafa", size: 100, gender: "Dama", price: 16, perfumeId: 57, fragranticaId: 94967 },
  { name: "Sublime", brand: "Lattafa", size: 100, gender: "Unisex", price: 12, perfumeId: null, fragranticaId: 83309 },
  { name: "Teriaq", brand: "Lattafa", size: 100, gender: "Unisex", price: 14, perfumeId: null, fragranticaId: 89850 },
  { name: "Teriaq Intense", brand: "Lattafa", size: 100, gender: "Dama", price: 14, perfumeId: 38, fragranticaId: 99586 },
  { name: "Tharwah Gold", brand: "Lattafa", size: 100, gender: "Unisex", price: 14, perfumeId: null, fragranticaId: 82004 },
  { name: "Tharwah Silver", brand: "Lattafa", size: 100, gender: "Caballero", price: 14, perfumeId: 220, fragranticaId: 82005 },
  { name: "The Kingdom Men", brand: "Lattafa", size: 100, gender: "Caballero", price: 12, perfumeId: 48, fragranticaId: 97995 },
  { name: "The Kingdom Woman", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 47, fragranticaId: 98648 },
  { name: "Vanilla Freak", brand: "Lattafa", size: 100, gender: "Unisex", price: 16, perfumeId: 42, fragranticaId: 114400 },
  { name: "Velvet Rose", brand: "Lattafa", size: 100, gender: "Dama", price: 11, perfumeId: 62, fragranticaId: 76867 },
  { name: "Victoria", brand: "Lattafa", size: 100, gender: "Dama", price: 14, perfumeId: 40, fragranticaId: 102906 },
  { name: "Vintage Radio", brand: "Lattafa", size: 100, gender: "Caballero", price: 13, perfumeId: 148, fragranticaId: 89454 },
  { name: "Whipped Pleasure", brand: "Lattafa", size: 100, gender: "Unisex", price: 16, perfumeId: 46, fragranticaId: 114397 },
  { name: "Yara", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 131, fragranticaId: 76880 },
  { name: "Yara Candy", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 228, fragranticaId: 95752 },
  { name: "Yara Elixir", brand: "Lattafa", size: 100, gender: "Dama", price: 14, perfumeId: 230, fragranticaId: 117615 },
  { name: "Yara Moi", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 133, fragranticaId: 80722 },
  { name: "Yara Tous", brand: "Lattafa", size: 100, gender: "Dama", price: 12, perfumeId: 132, fragranticaId: 83320 },

  // ==================== ZIMAYA (11) ====================
  { name: "Anhaar Valley", brand: "Zimaya", size: 100, gender: "Unisex", price: 11, perfumeId: 258, fragranticaId: 97032 },
  { name: "Evolution", brand: "Zimaya", size: 100, gender: "Dama", price: 11, perfumeId: 248, fragranticaId: 103823 },
  { name: "Fatima Pink", brand: "Zimaya", size: 100, gender: "Dama", price: 12, perfumeId: 254, fragranticaId: 92817 },
  { name: "Fatima Velvet", brand: "Zimaya", size: 100, gender: "Dama", price: 12, perfumeId: 255, fragranticaId: 120898 },
  { name: "Grandeur", brand: "Zimaya", size: 100, gender: "Dama", price: 11, perfumeId: 251, fragranticaId: 92578 },
  { name: "Hayam", brand: "Zimaya", size: 100, gender: "Dama", price: 11, perfumeId: 257, fragranticaId: 92593 },
  { name: "Is Great", brand: "Zimaya", size: 100, gender: "Dama", price: 11, perfumeId: 252, fragranticaId: 92588 },
  { name: "Only You", brand: "Zimaya", size: 100, gender: "Dama", price: 12, perfumeId: 256, fragranticaId: 92819 },
  { name: "Tiramisu Caramel", brand: "Zimaya", size: 100, gender: "Unisex", price: 13, perfumeId: 223, fragranticaId: 98691 },
  { name: "Tiramisu Coco", brand: "Zimaya", size: 100, gender: "Unisex", price: 13, perfumeId: 249, fragranticaId: 98690 },
  { name: "Zimaya Charisma", brand: "Zimaya", size: 100, gender: "Dama", price: 11, perfumeId: null, fragranticaId: 103119 },
];
